nodeLinker: node-modules

npmScopes:
  mistho:
    npmAlwaysAuth: true
    npmAuthToken: "${MISTHO_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
